BEGIN TRANSACTION;
ALTER TABLE events ADD COLUMN notification VARCHAR(50);
ALTER TABLE events ADD COLUMN emails_notification LONGTEXT;
ALTER TABLE events ADD COLUMN endtime DATETIME;
ALTER TABLE events ADD COLUMN each_repeat  INTEGER;
ALTER TABLE events ADD COLUMN days_repeat VARCHAR(30);
COMMIT;
